### ISSUE TITLE
PyPI release?

### ISSUE THREAD

**Issue by nicoddemus** [ansible/pytest-mp#2]
Hi,

Any plans for a PyPI release? I understand it is an early beta, but I believe it would be fine to publish a `0.0.1` version as it stands anyway. 😁 

I wanted to create a conda package for this plugin in https://conda-forge.org/, but for that I need a PyPI package or at least a tag in the repository.

**Comment by rmfitzpatrick** [comment]
Great suggestion!  This will definitely be registered w/ PyPI, but I intended to hold off until some edge cases in runs with multiple strategies are addressed.  Will be shooting to at least get some test coverage for them asap.

**Comment by nicoddemus** [comment]
Awesome, thanks!

**Comment by rmfitzpatrick** [comment]
@nicoddemus I've uploaded to [pypi](https://pypi.python.org/pypi/pytest-mp) and tagged a 0.0.1.  Thanks for your interest in making a conda package.

**Comment by nicoddemus** [comment]
Hi @rmfitzpatrick, thanks for the ping!

Just realized that this release doesn't support Python 3 though (#3), so I won't be able to create a conda-forge package for now.

Cheers!
